# Generated by Django 6.0.2 on 2026-04-26 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_poste', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cv_photos/')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('template_choisi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cvs', to='templates.template')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diplome', models.CharField(max_length=150)),
                ('etablissement', models.CharField(max_length=150)),
                ('annee', models.IntegerField()),
                ('mention', models.CharField(blank=True, max_length=50, null=True)),
                ('cvprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cv.cvprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poste', models.CharField(max_length=150)),
                ('entreprise', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('cvprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cv.cvprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('langue', models.CharField(max_length=100)),
                ('niveau', models.CharField(help_text='Ex: A1, B2, Courant', max_length=50)),
                ('cvprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cv.cvprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.IntegerField(help_text='Niveau de 1 à 100 par exemple')),
                ('cvprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='cv.cvprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
