# Generated by Django 6.0.2 on 2026-05-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
