# Generated by Django 6.0.2 on 2026-05-11 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_cvprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
