# Generated by Django 6.0.2 on 2026-05-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_cvprofile_created_at_cvprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='langue',
            field=models.CharField(choices=[('Français', 'Français'), ('Anglais', 'Anglais'), ('Arabe', 'Arabe'), ('Turc', 'Turc'), ('Allemand', 'Allemand'), ('Espagnol', 'Espagnol'), ('Italien', 'Italien'), ('Portugais', 'Portugais'), ('Autre', 'Autre')], help_text='Choisissez une langue', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='niveau',
            field=models.CharField(choices=[('A1', 'A1 - Débutant'), ('A2', 'A2 - Élémentaire'), ('B1', 'B1 - Intermédiaire'), ('B2', 'B2 - Avancé'), ('C1', 'C1 - Autonome'), ('C2', 'C2 - Maîtrise'), ('Courant', 'Courant'), ('Natif', 'Natif')], help_text='Choisissez votre niveau', max_length=50),
        ),
    ]
