# Generated by Django 6.0.2 on 2026-05-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_skill_description_skill_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='experience',
        ),
    ]
